export const similarWordGroups = [
  ['Basketball', 'Volleyball', 'Football'],
  ['Apple', 'Orange', 'Peach'],
  ['Cat', 'Dog', 'Rabbit'],
  ['Car', 'Bus', 'Truck'],
  ['Cup', 'Bottle', 'Glass'],
  ['Sun', 'Moon', 'Star'],
  ['Chair', 'Table', 'Stool'],
  ['Pen', 'Pencil', 'Marker'],
  ['Flower', 'Rose', 'Tulip'],
  ['Shoe', 'Boot', 'Sneaker'],
  ['Fish', 'Goldfish', 'Tuna'],
  ['Tree', 'Pine Tree', 'Palm Tree'],
  ['Fork', 'Spoon', 'Knife'],
  ['Hat', 'Cap', 'Helmet'],
  ['Boat', 'Ship', 'Canoe'],
  ['Clock', 'Watch', 'Timer'],
  ['House', 'Cabin', 'Castle'],
  ['Cake', 'Cupcake', 'Donut'],
  ['Camera', 'Phone', 'Tablet'],
  ['Bike', 'Motorcycle', 'Scooter'],
  ['Cloud', 'Smoke', 'Fog'],
  ['Duck', 'Chicken', 'Penguin'],
]

export const generalWords = [
  'Umbrella',
  'Key',
  'Rocket',
  'Crown',
  'Book',
  'Lamp',
  'Candle',
  'Drum',
  'Leaf',
  'Pizza',
  'Balloon',
  'Backpack',
  'Bicycle',
  'Bridge',
  'Comb',
  'Door',
  'Feather',
  'Glasses',
  'Hammer',
  'Heart',
  'Ice Cream',
  'Kite',
  'Ladder',
  'Mountain',
  'Mushroom',
  'Scissors',
  'Toothbrush',
  'Train',
  'Treasure Chest',
  'Television',
  'Guitar',
  'Bell',
  'Envelope',
  'Gift',
  'Flag',
  'Anchor',
  'Ring',
]

export const wordPacks = {
  general: {
    name: 'General',
    generalWords,
    similarWordGroups,
  },

  animals: {
    name: 'Animals',

    generalWords: [
      'Elephant',
      'Giraffe',
      'Monkey',
      'Bear',
      'Panda',
      'Cow',
      'Pig',
      'Sheep',
      'Goat',
      'Mouse',
      'Snake',
      'Octopus',
      'Crab',
      'Spider',
      'Owl',
      'Eagle',
      'Parrot',
      'Kangaroo',
      'Koala',
      'Camel',
      'Rhino',
      'Hippo',
      'Deer',
      'Fox',
      'Wolf',
      'Seal',
      'Bat',
      'Snail',
      'Ant',
      'Crocodile',
    ],

    similarWordGroups: [
      ['Cat', 'Dog', 'Rabbit'],
      ['Fish', 'Goldfish', 'Tuna'],
      ['Duck', 'Chicken', 'Penguin'],
      ['Lion', 'Tiger', 'Leopard'],
      ['Shark', 'Whale', 'Dolphin'],
      ['Horse', 'Donkey', 'Zebra'],
      ['Frog', 'Turtle', 'Lizard'],
      ['Bee', 'Butterfly', 'Ladybug'],
    ],
  },

  food: {
    name: 'Food',

    generalWords: [
      'Sushi',
      'Bread',
      'Cheese',
      'Egg',
      'Bacon',
      'Steak',
      'Chicken',
      'Taco',
      'Hot Dog',
      'Popcorn',
      'Ice Cream',
      'Watermelon',
      'Strawberry',
      'Pineapple',
      'Broccoli',
      'Donut Hole',
      'Soup',
      'Salad',
      'Fries',
      'Hotpot',
      'Dumpling',
      'Croissant',
      'Pretzel',
      'Muffin',
      'Pie',
      'Avocado',
      'Corn',
      'Pumpkin',
      'Onion',
      'Garlic',
    ],

    similarWordGroups: [
      ['Apple', 'Orange', 'Peach'],
      ['Cake', 'Cupcake', 'Donut'],
      ['Pizza', 'Burger', 'Sandwich'],
      ['Cookie', 'Candy', 'Chocolate'],
      ['Rice', 'Noodles', 'Pasta'],
      ['Carrot', 'Potato', 'Tomato'],
      ['Coffee', 'Tea', 'Milk'],
      ['Pancake', 'Waffle', 'Toast'],
    ],
  },

  sports: {
    name: 'Sports',

    generalWords: [
      'Golf',
      'Hockey',
      'Bowling',
      'Rugby',
      'Archery',
      'Gymnastics',
      'Fencing',
      'Kayaking',
      'Climbing',
      'Soccer',
      'Fishing',
      'Rowing',
      'Sailing',
      'Weightlifting',
      'Judo',
      'Taekwondo',
      'Pole Vault',
      'Long Jump',
      'High Jump',
      'Darts',
      'Horse Racing',
      'Water Polo',
      'Handball',
      'Lacrosse',
      'Billiards',
      'Snooker',
      'Curling',
      'Triathlon',
      'Marathon',
      'Parkour',
    ],

    similarWordGroups: [
      ['Basketball', 'Volleyball', 'Football'],
      ['Tennis', 'Badminton', 'Table Tennis'],
      ['Skiing', 'Snowboarding', 'Skating'],
      ['Swimming', 'Diving', 'Surfing'],
      ['Boxing', 'Wrestling', 'Karate'],
      ['Baseball', 'Cricket', 'Softball'],
      ['Cycling', 'Skateboarding', 'Scootering'],
      ['Running', 'Walking', 'Hiking'],
    ],
  },

  transport: {
    name: 'Transport',

    generalWords: [
      'Bicycle',
      'Submarine',
      'Rocket',
      'Tractor',
      'Skateboard',
      'Cable Car',
      'Hot Air Balloon',
      'Jeep',
      'Hovercraft',
      'Spaceship',
      'Monorail',
      'Rickshaw',
      'Gondola',
      'Segway',
      'Bulldozer',
      'Excavator',
      'Forklift',
      'Dump Truck',
      'Tank',
      'Glider',
      'Parachute',
      'Snowmobile',
      'Golf Cart',
      'Camper Van',
      'Caravan',
      'Jet Ski',
      'Raft',
      'Lifeboat',
      'Wheelchair',
      'Unicycle',
    ],

    similarWordGroups: [
      ['Car', 'Bus', 'Truck'],
      ['Boat', 'Ship', 'Canoe'],
      ['Bike', 'Motorcycle', 'Scooter'],
      ['Plane', 'Helicopter', 'Jet'],
      ['Train', 'Tram', 'Subway'],
      ['Taxi', 'Van', 'Limousine'],
      ['Ferry', 'Sailboat', 'Yacht'],
      ['Ambulance', 'Fire Truck', 'Police Car'],
    ],
  },

  nature: {
    name: 'Nature',

    generalWords: [
      'Leaf',
      'Mushroom',
      'Rainbow',
      'Beach',
      'Waterfall',
      'Forest',
      'Island',
      'Cave',
      'Snowflake',
      'Lightning',
      'Wave',
      'Desert',
      'Grass',
      'Bush',
      'Cactus',
      'Cliff',
      'Glacier',
      'Canyon',
      'Valley',
      'Water',
      'Sand',
      'Shell',
      'Coral',
      'Vine',
      'Bamboo',
      'Acorn',
      'Pond',
      'Meadow',
      'Swamp',
      'Reef',
    ],

    similarWordGroups: [
      ['Sun', 'Moon', 'Star'],
      ['Flower', 'Rose', 'Tulip'],
      ['Tree', 'Pine Tree', 'Palm Tree'],
      ['Cloud', 'Smoke', 'Fog'],
      ['River', 'Lake', 'Ocean'],
      ['Mountain', 'Hill', 'Volcano'],
      ['Rain', 'Snow', 'Hail'],
      ['Rock', 'Stone', 'Pebble'],
    ],
  },
} as const;

export type WordPackTheme = keyof typeof wordPacks;