export const similarWordGroups = [
  ['Basketball', 'Volleyball', 'Football'],
  ['Apple', 'Orange', 'Peach'],
  ['Cat', 'Dog', 'Rabbit'],
  ['Car', 'Bus', 'Truck'],
  ['Cup', 'Bottle', 'Glass'],
  ['Sun', 'Moon', 'Star'],
  ['Chair', 'Table', 'Stool'],
  ['Pen', 'Pencil', 'Marker'],
  ['Flower', 'Rose', 'Tulip'],
  ['Shoe', 'Boot', 'Sneaker'],
  ['Fish', 'Goldfish', 'Tuna'],
  ['Tree', 'Pine Tree', 'Palm Tree'],
  ['Fork', 'Spoon', 'Knife'],
  ['Hat', 'Cap', 'Helmet'],
  ['Boat', 'Ship', 'Canoe'],
  ['Clock', 'Watch', 'Timer'],
  ['House', 'Cabin', 'Castle'],
  ['Cake', 'Cupcake', 'Donut'],
  ['Camera', 'Phone', 'Tablet'],
  ['Bike', 'Motorcycle', 'Scooter'],
  ['Cloud', 'Smoke', 'Fog'],
  ['Duck', 'Chicken', 'Penguin'],
]

export const generalWords = [
  'Umbrella',
  'Key',
  'Camera',
  'Rocket',
  'Crown',
  'Book',
  'House',
  'Lamp',
  'Phone',
  'Candle',
  'Drum',
  'Leaf',
  'Boat',
  'Pizza',
  'Balloon',
  'Backpack',
  'Bicycle',
  'Bridge',
  'Cake',
  'Castle',
  'Cloud',
  'Comb',
  'Door',
  'Feather',
  'Fork',
  'Glasses',
  'Hammer',
  'Hat',
  'Heart',
  'Ice Cream',
  'Kite',
  'Ladder',
  'Mountain',
  'Mushroom',
  'Scissors',
  'Spoon',
  'Toothbrush',
  'Train',
  'Treasure Chest',
  'Television',
  'Guitar',
  'Bell',
  'Camera',
  'Envelope',
  'Gift',
  'Flag',
  'Anchor',
  'Ring',
]