export const similarWordGroups = [
  ['Basketball', 'Volleyball', 'Football'],
  ['Apple', 'Orange', 'Peach'],
  ['Cat', 'Dog', 'Rabbit'],
  ['Car', 'Bus', 'Truck'],
  ['Cup', 'Bottle', 'Glass'],
  ['Sun', 'Moon', 'Star'],
  ['Chair', 'Table', 'Stool'],
  ['Pen', 'Pencil', 'Marker'],
  ['Flower', 'Rose', 'Tulip'],
  ['Shoe', 'Boot', 'Sneaker'],
  ['Fish', 'Goldfish', 'Tuna'],
  ['Tree', 'Pine Tree', 'Palm Tree'],
]

export const generalWords = [
  'Umbrella',
  'Clock',
  'Key',
  'Camera',
  'Rocket',
  'Crown',
  'Flower',
  'Book',
  'Shoe',
  'Fish',
  'House',
  'Tree',
  'Lamp',
  'Phone',
  'Candle',
  'Drum',
  'Leaf',
  'Boat',
  'Watch',
  'Pizza',
]